# Generated by Django 4.2.2 on 2023-09-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_traincategory_ticket_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.traincategory'),
        ),
    ]
