# Generated by Django 4.2.2 on 2023-09-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_train_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
